unknown option '--skip-rebase' #85
```
cleancss -O2 --skip-rebase -o /path/to/file/style.css
error: unknown option '--skip-rebase'
```

reference issue:  #85

* update node clean-css using exact version clean-css@3.4.24
* fix typo on README (part example and license)

Note:
This is just **Temporary** solution, before you make an update to functionality of this package. So people like me can use your package properly, specially for minify css code.

Regard's
ian